services:
    
    SintraPimcoreBundle\EventListener\SintraPimcoreObjectListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd, method: onPreAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete, method: onPostDelete }
