services:
    
    optionsproviders.productcategoryoptionsprovider:
        class: SintraPimcoreBundle\OptionsProviders\ProductCategoryOptionsProvider
        public: true
    
    optionsproviders.productattributesetoptionsprovider:
        class: SintraPimcoreBundle\OptionsProviders\ProductAttributeSetOptionsProvider
        public: true
